### ISSUE TITLE
Conso live error : energy dashboard consumption is bigger than expected (sometimes)

### ISSUE THREAD

**Issue by LudoARN** [jugla/keyatome#12] opened 2022-03-17 20:05 UTC
Hello,

i'm very surprised to find my daily consumption, totaly different than the official consumption,
could you help me to find the problem ?

![image](https://user-images.githubusercontent.com/81586322/158886299-f8dc42e2-87da-43b7-9ad5-d6fda0653d73.png)

Thanks

**Comment by jugla** [comment] 2022-03-19 22:03
Please can you look, if the live data is correct ?

**Comment by jugla** [comment] 2022-03-22 06:54
No news ?

**Comment by sensei73** [comment] 2022-03-23 05:05
Hello, I have also this problem. It happened sometimes, here some data that seems weird as the state should be linear.
<img width="910" alt="image" src="https://user-images.githubusercontent.com/7949007/159627638-9603e747-eec6-4f21-89b7-ec7612db79d5.png">
<img width="344" alt="image" src="https://user-images.githubusercontent.com/7949007/159627697-4ff9ca6d-735f-4792-92cf-cfffef59348a.png">

**Comment by jugla** [comment] 2022-03-23 07:26
strange.
I will look in sensor attribute option if nothing strange.
Please can you take a picture of live data curve and daily curve.
Thanks in advance

**Comment by sensei73** [comment] 2022-03-23 07:31
this one seems normal.
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/7949007/159646671-95e7afeb-1047-43d6-91ae-095185677014.png">

this one should be linear!
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/7949007/159646403-19598c74-54d3-4fbd-ad56-f962cbb10ec3.png">

**Comment by jugla** [comment] 2022-03-23 07:38
Agree!
In the logs do you have trace that seems strange?

**Comment by sensei73** [comment] 2022-03-23 08:17
I have this error multiples times:

```
2022-03-23 02:12:45 WARNING (SyncWorker_8) [custom_components.keyatome.sensor] Live Data : Missing last value in values: {'isConnected': True, 'time': '2022-03-23T02:12:45+01:00', 'timeLimitBeforePowerFailure': -1}
2022-03-23 02:12:46 ERROR (SyncWorker_8) [custom_components.keyatome.sensor] Live Data : Missing last value in values: {'isConnected': True, 'time': '2022-03-23T02:12:46+01:00', 'timeLimitBeforePowerFailure': -1}
```

**Comment by LudoARN** [comment] 2022-03-23 20:42
Hello,

same problem today :

Logger: custom_components.keyatome.sensor
Source: custom_components/keyatome/sensor.py:399
Integration: KeyAtome Linky ([documentation](https://github.com/jugla/keyatome), [issues](https://github.com/jugla/keyatome/issues))
First occurred: 22 mars 2022, 19:48:22 (26 occurrences)
Last logged: 19:48:59

    Live Data : Missing last value in values: {'isConnected': True, 'time': '2022-03-23T02:19:12+01:00', 'timeLimitBeforePowerFailure': -1}
    Live Data : Missing last value in values: {'isConnected': True, 'time': '2022-03-23T02:19:43+01:00', 'timeLimitBeforePowerFailure': -1}
    Live Data : Missing last value in values: {'isConnected': True, 'time': '2022-03-23T02:20:44+01:00', 'timeLimitBeforePowerFailure': -1}
    Live Data : Missing last value in values: {'isConnected': True, 'time': '2022-03-23T02:21:15+01:00', 'timeLimitBeforePowerFailure': -1}
    Live Data : Missing last value in values: None

**Comment by jugla** [comment] 2022-03-24 08:54
Thanks
At one moment the TotalEnergies server sends back no data ==> live data curve seems to be ok/robust. 
Energy dashboard is based on "daily consumption" `atome_daily` => for HA , it shall be increasing along the day .

Please can you look in the homeassistant.log file to see if there is an exception or whatever for this sensor.atome_daily.

By the way : 
- do you use direclty the sensor provided by `keyatome` integration or have you templating ?
- do you have single subscription or several ?

**Comment by sensei73** [comment] 2022-03-24 09:30
Since I restarted HA, I don't have the logs anymore :'(
I do not use templating and I have only one subscription.

today, everything seems ok so far! 

screenshot of yesterday (the first hours between 0h and 6h are a bit messy as I tried to correct the mysql tables) 
<img width="933" alt="image" src="https://user-images.githubusercontent.com/7949007/159885804-e7684df8-9137-439f-8098-9b9b2d7dbc93.png">

**Comment by jugla** [comment] 2022-03-24 09:37
Thanks, I suspect that when there is no value from Total Energies, the `None` value gives to HA is not the expected one.
I mean if `None` is used as `0` (zero) then I have to change something

**Comment by sensei73** [comment] 2022-03-24 09:46
Longterm statistics automatically drops unavailable/none values. If "0" is pass instead of none or unavailable, it automatically increases value as it's a new "reset".

I also drop the "float" in this code for the same reason!
```
template:
  - sensor:
      - name: atome_daily_price
        state: "{{ state_attr('sensor.atome_daily', 'price') | float }}"
        unit_of_measurement: 'EUR'
        state_class: total_increasing
        device_class: monetary
```

**Comment by jugla** [comment] 2022-03-24 09:48
Thanks !

**Comment by jugla** [comment] 2022-03-24 09:51
I think the consumption of 23r march is false.
If you have an appart or house the consumption is 40kw per day not not per hour.

Can you check the daily sensor.
Mine is messy  
![image](https://user-images.githubusercontent.com/59493499/159889773-1c4e4f55-4e8a-4a23-b1ed-1c14256ca67c.png)

**Comment by jugla** [comment] 2022-03-24 09:52
The back and force value is interpreted by energydash board as peak consumption

**Comment by sensei73** [comment] 2022-03-24 09:56
I barely use 15kw max per day.

mine also is messy
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/7949007/159890716-70b0d809-b94a-4bcb-bf40-50d14884efbc.png">

**Comment by jugla** [comment] 2022-03-24 09:58
Ok,
We have found the root cause.

**Comment by sensei73** [comment] 2022-03-24 10:03
Great! Sorry, I can just help point out what's wrong, I'm not good enough to help you with coding!

**Comment by jugla** [comment] 2022-03-24 10:05
I mean, thanks we have found the root cause, i.e. data received from server.
Now I wonder what i can do to remove wrong data or warn the user

**Comment by sensei73** [comment] 2022-03-24 10:08
I can see the logic:

IF data Between 00:00 and 23:55 is less Than previous Mesure and > 0 == DROP

**Comment by jugla** [comment] 2022-03-24 10:12
I think , I will create a "protected" value and "raw" value. In case ;-)

**Comment by sensei73** [comment] 2022-03-24 10:21
Thanks, let me know if you need more data or feedback.

**Comment by jugla** [comment] 2022-03-24 10:22
It's ok for time being :-)

**Comment by jugla** [comment] 2022-03-24 11:38
Please can you test V5.2.1 ?

**Comment by sensei73** [comment] 2022-03-24 12:18
Done! thanks for the quick update! Should I monitor some logs to see if it's working (dropping unusual values)?

**Comment by jugla** [comment] 2022-03-24 12:40
If something wrong, in the log, I've put the fllowing error :  `Period are strictly increasing except reset to zero`

**Comment by LudoARN** [comment] 2022-03-24 20:19
Thanks for your quick update (i use the version 5.2.2).
I hope it will work better in the next days, and the TotalEnergies server too.

**Comment by jugla** [comment] 2022-03-27 00:34
Hello
I will close the issue as there is no regression for time being.
If one day, the total energies sends data that are not increasing, then the 5.2.1/5.2.2 version will prevent from having strange consumption.

**Closed as completed by jugla** 2022-03-27 00:34 UTC
Labels: enhancement, explanation, server issue

**Comment by sensei73** [comment] 2022-04-03 06:34
<img width="399" alt="Capture d’écran 2022-04-03 à 08 31 44" src="https://user-images.githubusercontent.com/7949007/161414997-c3d3fbbb-baf5-4273-b8e1-c2e2e2c40bdb.png">
Working great!

**Comment by jugla** [comment] 2022-06-04 13:52
Thanks !
